// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNG40QAOojIII0WD4IpCEeWa1cZCmnguI',
    appId: '1:957464103967:android:64f7b7c3941a617a3f192a',
    messagingSenderId: '957464103967',
    projectId: 'fall-202e1',
    storageBucket: 'fall-202e1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzxsf0c-aeJ-DDE_HGimVLM0nBcEgNSLU',
    appId: '1:957464103967:ios:34c5c88b97900d343f192a',
    messagingSenderId: '957464103967',
    projectId: 'fall-202e1',
    storageBucket: 'fall-202e1.firebasestorage.app',
    iosBundleId: 'sn.isi.fallMouhamadoulamineL3glExamen',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnTK-z04vj0E-iZ-k0n6XAAC0CLQIReIM',
    authDomain: 'fall-202e1.firebaseapp.com',
    projectId: 'fall-202e1',
    storageBucket: 'fall-202e1.firebasestorage.com',
    messagingSenderId: '957464103967',
    appId: '1:957464103967:web:c90baef62e6669db3f192a',
      measurementId:'G-04RG2WWXJR'
  );

}